name: Generate ICS

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows me to manually trigger this workflow whenever I want

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest
          pip install -r requirements.txt  # Install all the libraries I need

      - name: Run script
        run: python main.py  # Run my Python script to generate the .ics file

      - name: Commit and push ICS file to main branch
        run: |
          git add soccer_schedule.ics  # Stage the .ics file for commit
          git commit -m "Update soccer_schedule.ics" || echo "No changes to commit"  # Commit changes
          git push origin main  # Push changes to the main branch
